[web]

# Port where web config will be accessible
port = 5000

[obs]

# Where the OBS WebSocket should connect to, default host is 'localhost'
host = "127.0.0.1"
port = 4455
password = "stillglaikit"

# Automatically change scenes when a game is in progress using slippi.
# Useful to avoid the "Waiting for game" screen
# true / false
scene_changer = true

#Scenes to automatically switch to when game starts and ends.
# Typically start_scene will contain an instance of Slippi Dolphin and end_scene one of a capture card or webcams
start_scene = "game"
end_scene = "splash"
browser_transition = "game-in (browser)"


# Length of clip (in seconds)
clip_length = 30

[startgg]

# start.gg API key and version - generate one at https://start.gg/admin/profile/developer
key = "025446143514ddd5187345ca3546cb42"

[slippi]

# Output folder for the .SLP files of the stream setup

# Gregor's directories
#"C:\Users\Public\Documents\Slippi"

# Cleo's directories
#"D:\SSBM\SlippiSpectate\cleo-wii"
#"D:\SSBM\Slippi\2024-0"

directory = "D:\SSBM\Slippi\2024-05"

# Only used for recording replays after an event
melee_iso = "C:\Users\Public\Documents\[SSBM]ScotlandStages.iso"

# Automatically keep track of match score
track_score = true

# Unless debugging, keep this false (duh) - games with less than 45 seconds playtime, under 120% damage dealt, games with CPUs, do not advance game score when false
# true / false
debug_mode = true